# name: Build & Deploy
# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy Laravel App
#         uses: appleboy/ssh-action@v0.1.2
#         with:
#           host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
#           key: ${{secrets.SSH_KEY}} # Private or public key of the server
#           username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
#           script: |
#             cd /var/www/ 
#             git clone https://soman-maharjan:Sm9841551187@github.com/soman-maharjan/blank-back.git
#             echo 'Deployment successful to digital ocean' 
